version: "3.9"

services:
  web:
    build: . 
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - mynetwork
    env_file:
      - .env 
  db:
    image: postgres
    environment:
      POSTGRES_USER: psp-dev  
      POSTGRES_PASSWORD: psp-dev
      POSTGRES_DB: psp-dev
    ports:
     - 5432:5432
    networks:
     - mynetwork
networks:
  mynetwork:
    driver: bridge