// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"time"
)

type Payable struct {
	ID            string
	ClientID      sql.NullString
	TransactionID sql.NullString
	Status        sql.NullString
	FeeAmount     sql.NullInt64
	Amount        sql.NullInt64
	PaymentDate   time.Time
	CreatedAt     time.Time
}

type Transaction struct {
	ID                   string
	ClientID             sql.NullString
	Description          sql.NullString
	Value                sql.NullInt64
	CardOwnerName        sql.NullString
	CardVerificationCode sql.NullString
	CardLastDigits       sql.NullString
	CardValidDate        time.Time
	PaymentMethod        sql.NullString
	CreatedAt            time.Time
}
