// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreatePayable(ctx context.Context, arg CreatePayableParams) error
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) error
	GetBalanceByStatuses(ctx context.Context, clientID sql.NullString) ([]GetBalanceByStatusesRow, error)
	GetPayableByID(ctx context.Context, id string) (Payable, error)
	GetTransactionByID(ctx context.Context, id string) (Transaction, error)
	GetTransactionsByClientID(ctx context.Context, clientID sql.NullString) ([]Transaction, error)
}

var _ Querier = (*Queries)(nil)
